### PR TITLE
chore!: DBTP-756 delete waf config

### PR DESCRIPTION
**Pull request by ejayesh**
Remove all code related to WAF, as this is no longer needed in the helper command

### CODE REVIEW

**Review by acodeninja — COMMENTED** [review]
Is this technically a breaking change?

**Comment by ejayesh** [comment]
> Is this technically a breaking change?

I wouldn't have thought so, as we havent use this anywhere.   Although the waf.yml file is present in the DW-deploy repo.

**Comment by WillGibson** [comment]
It is technically a breaking change, even if no-one is using it, and we agreed to be strict about applying it to prevent time spent talking about it.

Also, we need to decide on our release process!

**Comment by ejayesh** [comment]
Ok.

**Comment by ejayesh** [comment]
Link to the Release that will contain this change:  https://github.com/uktrade/copilot-tools/releases

**Review by WillGibson — APPROVED** [review]

**Pull request merged**
