### PR TITLE
DBTP-660 Add OpenTelemetry variables to manifest files

### PR DESCRIPTION
**Pull request by yusufsheiqh**
## Context

- Add OTel env vars to manifest template files
  - This is to setup observability (X-Ray) for services.
  - The sampling ratio is set at a default of 5%.
- Add `Dockerfile.debian` file
  - This is currently used for `copilot-python` as the Alpine Dockerfile does not support installing gRPC within a `poetry` context. This image should also be used for this repo in the near future to avoid issues like this from reoccurring.

### CODE REVIEW

**Review by acodeninja — COMMENTED** [review]
Looking good, my only wonder is if this might get expensive if we enable for everything?

**Comment by yusufsheiqh** [comment]
> Looking good, my only wonder is if this might get expensive if we enable for everything?

@acodeninja Would you suggest enabling on the `web`/public facing services as a default?

**Comment by acodeninja** [comment]
> @acodeninja Would you suggest enabling on the `web`/public facing services as a default?

I reckon we should to start off with, from my understanding though this will not be enabled unless the process is prefixed with the otel collector application.

**Review by acodeninja — APPROVED** [review]

**Review by WillGibson — APPROVED** [review]

**Review by ejayesh — APPROVED** [review]
lgtm

**Pull request merged**
